### ISSUE TITLE
no adaface loss in source code

### ISSUE THREAD

**Issue by chungphung** [liuf1990/CFSM#1]
Hi, I didnt find any code about adaface loss in your training source code for pretrained adaface AdaFace + CFSM model. Can you provide adaface loss source code for that model? 
The readme for CFSM model is hard to understand in the training with custom dataset part, can you also provide the custom dataset config for it too?

**Comment by liufeng2915** [comment]
Thank you for your interest in our work. <del> I will add the AdaFace loss soon. </del> The AdaFace loss was added.
